---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.2.4
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes" CHECK=test
  allow_failures:
    - rvm: 2.3.0
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "SCQpiBB9qpZAjBRk+b9D3cSCQfYpDgHPOdOc7djfGeB5yn1UbGg7uW1zshrshb4QMLfUgvsL4LsT0CYj7ilBerghgeySF5JWuZdk05W/7Iudls4btbxdVjqtALR7p02mnk40qHTR1Tdb/j0gXW9uigU6nQU9iCP+Poa1KF6PXpk="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
